# Generated by Django 2.2.6 on 2019-10-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
