# Generated by Django 2.2.6 on 2019-10-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191017_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name="nom d'utilisateur"),
        ),
    ]
