# Generated by Django 2.1.7 on 2019-10-08 12:13

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('piaf', '0001_initial'), ('piaf', '0002_paragraph_text'), ('piaf', '0003_auto_20191008_1139'), ('piaf', '0004_remove_paragraphbatch_article')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('progress', 'progress'), ('completed', 'completed')], default='pending', max_length=10)),
                ('participated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete='null', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete='cascade', related_name='paragraphs', to='piaf.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('paragraph', models.ForeignKey(on_delete='cascade', related_name='questions', to='piaf.Paragraph')),
                ('created_at', models.DateField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete='cascade', related_name='answers', to='piaf.Question'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParagraphBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('progress', 'progress'), ('completed', 'completed')], default='pending', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete='null', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='participated_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=None, on_delete='null', related_name='answers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraph',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('progress', 'progress'), ('completed', 'completed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='batch',
            field=models.ForeignKey(default=1, on_delete='cascade', related_name='paragraphs', to='piaf.ParagraphBatch'),
            preserve_default=False,
        ),
    ]
