# Generated by Django 2.1.7 on 2019-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piaf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
