# Generated by Django 2.1.7 on 2019-10-10 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('piaf', '0002_auto_20191010_1341'), ('piaf', '0003_remove_answer_end_position'), ('piaf', '0004_auto_20191010_1344')]

    dependencies = [
        ('piaf', '0001_squashed_0004_remove_paragraphbatch_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='end_position',
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete='null', related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
