# Generated by Django 2.1.7 on 2019-10-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piaf', '0002_auto_20191010_1341_squashed_0004_auto_20191010_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='start_position',
            new_name='index',
        ),
    ]
