# Generated by Django 2.1.7 on 2019-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piaf', '0003_auto_20191011_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reference',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.CharField(choices=[('religion', 'Religion'), ('geographie', 'Géographie'), ('histoire', 'Histoire'), ('sport', 'Sport'), ('art', 'Art'), ('societe', 'Société'), ('sciences', 'Sciences')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
