# Generated by Django 2.1 on 2019-12-12 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piaf', '0003_question_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelevancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(max_length=1)),
                ('score', models.PositiveIntegerField(max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete='cascade', related_name='relavancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
