# Generated by Django 2.1 on 2019-12-20 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piaf', '0004_userrelevancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelevancy',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='userrelevancy',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userrelevancy',
            name='user',
            field=models.ForeignKey(on_delete='cascade', related_name='relevancies', to=settings.AUTH_USER_MODEL),
        ),
    ]
