# Generated by Django 2.2.6 on 2019-10-15 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('piaf', '0005_paragraph_user'), ('piaf', '0006_auto_20191015_1334')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piaf', '0004_auto_20191015_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='user',
            field=models.ForeignKey(null=True, on_delete='null', to=settings.AUTH_USER_MODEL),
        ),
    ]
