# Generated by Django 2.1 on 2020-02-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piaf', '0005_auto_20191220_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
