# Generated by Django 2.1.7 on 2019-09-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_and_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seq2seqAnnotationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('start_offset', models.IntegerField()),
                ('seq2seqAnnotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq2seq_annotations_response', to='api.Seq2seqAnnotation')),
            ],
        ),
    ]
